name: Rustfmt

on:
  pull_request:
    branches: [ "*" ]
    paths:
      - "crates/**"

jobs:
  check-rust-format:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./crates
    steps:
      - uses: actions/checkout@v4
      - name: Install clippy
        run: rustup update && rustup component add clippy
      - name: Check format
        run: cargo fmt -- --check
      - name: Check format
        run: cargo fmt -- --check
        working-directory: ./crates/y-sweet-worker
