name: Staging Deploy

on:
  push:
    branches: [ "main" ]
    paths:
      - "crates/**"

env:
  CARGO_TERM_COLOR: always

jobs:
  staging-deploy:
    runs-on: ubuntu-latest-16-cores
    defaults:
      run:
        working-directory: ./crates/y-sweet-worker

    steps:
    - uses: actions/checkout@v3
    - uses: Swatinem/rust-cache@v2
      with:
        cache-on-failure: "true"
        # y-sweet-worker is excluded from the outer Cargo "workspace"
        # because it has a different target (wasm rather than system arch). We
        # still want to cache its output, so we do that here.
        # See: https://github.com/Swatinem/rust-cache
        workspaces: "crates -> target\ncrates/y-sweet-worker -> target"

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 19
    - run: npm ci
    - run: npm run deploy
      env:
        CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
